name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into Server and Pull Changes
      run: |
        echo "$SSH_KEY" > github_actions_deploy_key
        chmod 600 github_actions_deploy_key
        ssh -i ${{ secrets.SSH_USERNAME }}@${{ secrets.RASPBERRY_PI_IP }} << EOF
          cd ${{ secrets.TELEBOT_PATH }}
          git pull origin main
          pm2 restart telebot
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
